name = "sistem-sprin"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
AUTH_TRUST_HOST = "true"
AUTH_SECRET = "kuncirahasiapuslitbang2026sprin"
DATABASE_URL = "postgresql://postgres.jnqipntxgtwlounpgger:projectpuslitbang123@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true"
DIRECT_URL = "postgresql://postgres.jnqipntxgtwlounpgger:projectpuslitbang123@aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres"
