import { PrismaClient, Division } from '@prisma/client';

const prisma = new PrismaClient();

export interface RawPersonelEntry {
  no: number;
  name: string;
  rank: string;
  nrp: string;
  jabatan: string;
  division: Division;
  ket?: string;
}

export const personelPdfData: RawPersonelEntry[] = [
  // Halaman 1 (1 - 24)
  {
    no: 1,
    name: 'DIDI HAYAMANSYAH, S.H., S.I.K., M.H.',
    rank: 'BRIGADIR JENDERAL POLISI',
    nrp: '74040735',
    jabatan: 'KAPUSLITBANG POLRI',
    division: 'TAUD',
    ket: 'IV. D',
  },
  {
    no: 2,
    name: 'BUDI KARYONO, S.H.',
    rank: 'BRIGJEN POL',
    nrp: '70010202',
    jabatan: 'PENELITI ILMU KEPOLISIAN UTAMA TK. II PUSLITBANG POLRI',
    division: 'OPSNAL',
    ket: 'IV. D',
  },
  {
    no: 3,
    name: 'ANDREAS WIDIHANDOKO, S.H., M.H.',
    rank: 'KOMBES POL',
    nrp: '70070485',
    jabatan: 'SESPUSLITBANG POLRI',
    division: 'TAUD',
    ket: 'IV.C',
  },
  {
    no: 4,
    name: 'SAEFUDDIN MOHAMAD, S.I.K.',
    rank: 'KOMBES POL',
    nrp: '72070518',
    jabatan: 'KABIDGASOPSNAL PUSLITBANG POLRI',
    division: 'OPSNAL',
    ket: 'IV.C',
  },
  {
    no: 5,
    name: 'GUNO PITOYO, S.I.K., M.H.',
    rank: 'KOMBES POL',
    nrp: '72110542',
    jabatan: 'KABIDRIKWASTU PUSLITBANG POLRI',
    division: 'RIKUWASTU',
    ket: 'IV.C',
  },
  {
    no: 6,
    name: 'MUHAMMAD FAUZI, S.I.K., S.H., M.M.',
    rank: 'KOMBES POL',
    nrp: '73070715',
    jabatan: 'KABIDGASBIN PUSLITBANG POLRI',
    division: 'GASBIN',
    ket: 'IV.C',
  },
  {
    no: 7,
    name: 'Dr. ENDRO SULAKSONO, S.Kom., M.Si.',
    rank: 'KOMBES POL',
    nrp: '69120114',
    jabatan: 'KABAGLABTEKPOL PUSLITBANG POLRI',
    division: 'TEKPOL',
    ket: 'IV.C',
  },
  {
    no: 8,
    name: 'YUDY CHANDRA E, S.I.K., M.H.',
    rank: 'KOMBES POL',
    nrp: '74070783',
    jabatan: 'PENELITI ILMU KEPOLISIAN MADYA TK. I PUSLITBANG POLRI',
    division: 'OPSNAL',
    ket: 'IV.C',
  },
  {
    no: 9,
    name: 'DODI DARJANTO, S.I.K., M.H.',
    rank: 'KOMBES POL',
    nrp: '74120631',
    jabatan: 'PENELITI ILMU KEPOLISIAN MADYA TK. I PUSLITBANG POLRI',
    division: 'OPSNAL',
    ket: 'IV. C',
  },
  {
    no: 10,
    name: 'ARTANTO, S.I.K., M.Si.',
    rank: 'KOMBES POL',
    nrp: '72120382',
    jabatan: 'PENELITI ILMU KEPOLISIAN MADYA TK. I PUSLITBANG POLRI',
    division: 'OPSNAL',
    ket: 'IV.C',
  },
  {
    no: 11,
    name: 'ADE DJADJA SUBAGDJA, S.I.K., M.H.',
    rank: 'KOMBES POL',
    nrp: '71080522',
    jabatan: 'PENELITI ILMU KEPOLISIAN MADYA TK. II PUSLITBANG POLRI',
    division: 'GASBIN',
    ket: 'IV.C',
  },
  {
    no: 12,
    name: 'MUHAMMAD BUDI ARIYANTO, S.I.K., M.H.',
    rank: 'KOMBES POL',
    nrp: '74010610',
    jabatan: 'PENELITI ILMU KEPOLISIAN MADYA TK. II PUSLITBANG POLRI',
    division: 'GASBIN',
    ket: 'IV.C',
  },
  {
    no: 13,
    name: 'KATRINA J. RATU, S.Sos.',
    rank: 'KOMBES POL',
    nrp: '70060465',
    jabatan: 'PENELITI ILMU KEPOLISIAN MADYA TK.II PUSLITBANG POLRI',
    division: 'RIKUWASTU',
    ket: 'IV.C',
  },
  {
    no: 14,
    name: 'ADY SAVART PENATARAN SIMANJUNTAK, S.H., S.I.K.',
    rank: 'KOMBES POL',
    nrp: '74030653',
    jabatan: 'PENELITI ILMU KEPOLISIAN MADYA TK. II PUSLITBANG POLRI',
    division: 'RIKUWASTU',
    ket: 'IV.C',
  },
  {
    no: 15,
    name: 'YULIANI, S.H., M.M.',
    rank: 'KOMBES POL',
    nrp: '70070799',
    jabatan: 'PENELITI ILMU KEPOLISIAN MADYA TK. II PUSLITBANG POLRI',
    division: 'GASBIN',
    ket: 'IV.C (penugasan luar struktur)',
  },
  {
    no: 16,
    name: 'RIDO ROLLY MARULI PARSAORAN PURBA, S.I.K., M.H.',
    rank: 'KOMBES POL',
    nrp: '79121294',
    jabatan: 'PENELITI ILMU KEPOLISIAN MADYA TK. III PUSLITBANG POLRI',
    division: 'OPSNAL',
    ket: 'IV.C',
  },
  {
    no: 17,
    name: 'HIDAYAT ASYKURI GINTING, S.I.K.',
    rank: 'KOMBES POL',
    nrp: '76010855',
    jabatan: 'PENELITI ILMU KEPOLISIAN MADYA TK. III PUSLITBANG POLRI',
    division: 'OPSNAL',
    ket: 'IV.C',
  },
  {
    no: 18,
    name: 'NANY HARTATI PRIBADI, S.I.K., M.I.K.',
    rank: 'KOMBES POL',
    nrp: '76110054',
    jabatan: 'PENELITI ILMU KEPOLISIAN MADYA TK. III PUSLITBANG POLRI',
    division: 'GASBIN',
    ket: 'IV.C',
  },
  {
    no: 19,
    name: 'TONNY KURNIAWAN, S.I.K.',
    rank: 'KOMBES POL',
    nrp: '79060818',
    jabatan: 'PENELITI ILMU KEPOLISIAN MADYA TK. III PUSLITBANG POLRI',
    division: 'GASBIN',
    ket: 'IV.C',
  },
  {
    no: 20,
    name: 'Dr. MIFTA HADI SAFII, S.I.K., M.I.K.',
    rank: 'KOMBES POL',
    nrp: '79091272',
    jabatan: 'ANALIS KEBIJAKAN MADYA BIDANG LITBANG PUSLITBANG POLRI',
    division: 'OPSNAL',
    ket: 'IV.C (BKO)',
  },
  {
    no: 21,
    name: 'MOH. NURHIDAYAT, S.H., S.I.K., M.M.',
    rank: 'KOMBES POL',
    nrp: '81070636',
    jabatan: 'PENELITI ILMU KEPOLISIAN MADYA TK. III PUSLITBANG POLRI',
    division: 'RIKUWASTU',
    ket: 'IV.C',
  },
  {
    no: 22,
    name: 'MURJOKO BUDOYONO, S.I.K.',
    rank: 'KOMBES POL',
    nrp: '71010448',
    jabatan: 'PENELITI ILMU KEPOLISIAN MADYA TK. III PUSLITBANG POLRI',
    division: 'RIKUWASTU',
    ket: 'IV.C',
  },
  {
    no: 23,
    name: 'IDA BAGUS MADE WINARTA, S.I.K., M.M.',
    rank: 'KOMBES POL',
    nrp: '77061074',
    jabatan: 'PENELITI ILMU KEPOLISIAN MADYA TK. III PUSLITBANG POLRI',
    division: 'TEKPOL',
    ket: 'IV.C',
  },
  {
    no: 24,
    name: 'HAFIDH SUSILO HERLAMBANG, S.I.K., M.H.',
    rank: 'KOMBES POL',
    nrp: '79091273',
    jabatan: 'PENELITI ILMU KEPOLISIAN MADYA TK. III PUSLITBANG POLRI',
    division: 'TEKPOL',
    ket: 'IV.C',
  },

  // Halaman 2 (25 - 46)
  {
    no: 25,
    name: 'ROBY SEPTIADI, S.I.K.',
    rank: 'KOMBES POL',
    nrp: '78090913',
    jabatan: 'PENELITI ILMU KEPOLISIAN MADYA TK. III PUSLITBANG POLRI',
    division: 'OPSNAL',
    ket: 'IV.C',
  },
  {
    no: 26,
    name: 'WAHYUDI WICAKSANA, S.I.K.',
    rank: 'KOMBES POL',
    nrp: '76090778',
    jabatan: 'PENELITI ILMU KEPOLISIAN MADYA TK. III PUSLITBANG POLRI',
    division: 'OPSNAL',
    ket: 'IV.C',
  },
  {
    no: 27,
    name: 'MAX MARINERS, S.I.K.',
    rank: 'KOMBES POL',
    nrp: '76010876',
    jabatan: 'PENELITI ILMU KEPOLISIAN MADYA TK. III PUSLITBANG POLRI',
    division: 'RIKUWASTU',
    ket: 'IV.C',
  },
  {
    no: 28,
    name: 'BUDI ADHY BUONO, S.H., S.I.K., M.H.',
    rank: 'KOMBES POL',
    nrp: '79021175',
    jabatan: 'PENELITI ILMU KEPOLISIAN MADYA TK. III PUSLITBANG POLRI',
    division: 'TEKPOL',
    ket: 'IV.C',
  },
  {
    no: 29,
    name: 'ADHI SETYAWAN, S.I.K., M.H.',
    rank: 'AKBP',
    nrp: '79041517',
    jabatan: 'PENELITI ILMU KEPOLISIAN MADYA TK. III PUSLITBANG POLRI',
    division: 'OPSNAL',
    ket: 'IV.B',
  },
  {
    no: 30,
    name: 'I NENGAH SUKIARTA, S.S.',
    rank: 'AKBP',
    nrp: '76040937',
    jabatan: 'KASUBBAG KERMA SETPUSLITBANG POLRI',
    division: 'KERMA',
    ket: 'IV.B',
  },
  {
    no: 31,
    name: 'UJANG DARMAWAN HADI SAPUTRA, S.H., S.I.K., M.M., M.I.K.',
    rank: 'AKBP',
    nrp: '81101066',
    jabatan: 'PENELITI ILMU KEPOLISIAN MUDA TK. I PUSLITBANG POLRI',
    division: 'OPSNAL',
    ket: 'IV.B',
  },
  {
    no: 32,
    name: 'ADE CHADIJAH, S.Sos.',
    rank: 'AKBP',
    nrp: '71030356',
    jabatan: 'KASUBBID SDM BIDGASBIN PUSLITBANG POLRI',
    division: 'GASBIN',
    ket: 'IV.B',
  },
  {
    no: 33,
    name: 'RUSDI, A.Md., S.E.',
    rank: 'AKBP',
    nrp: '72060521',
    jabatan: 'KASUBBIDGASTIN BIDGASOPSNAL PUSLITBANG POLRI',
    division: 'OPSNAL',
    ket: 'IV.B',
  },
  {
    no: 34,
    name: 'SEPTI ASTUTI, S.T., M.A.',
    rank: 'AKBP',
    nrp: '75091084',
    jabatan: 'KASUBBIDPAL BIDRIKWASTU PUSLITBANG POLRI',
    division: 'RIKUWASTU',
    ket: 'IV.B',
  },
  {
    no: 35,
    name: 'IWAN SEBASTIAN, S.ST., S.H., M.H.',
    rank: 'AKBP',
    nrp: '80081440',
    jabatan: 'KASUBBAG UJISARTRANS BAGLABTEKPOL PUSLITBANG POLRI',
    division: 'TEKPOL',
    ket: 'IV.B DIK',
  },
  {
    no: 36,
    name: 'JOSSY ANDRIANTO, S.ST., M.M., CPHR.',
    rank: 'AKBP',
    nrp: '80051326',
    jabatan: 'KASUBBAGUJISENJATA BAGLABTEKPOL PUSLITBANG POLRI',
    division: 'TEKPOL',
    ket: 'IV.B DIK',
  },
  {
    no: 37,
    name: 'INDRAS BUDI PURNOMO, S.I.K., M.M.',
    rank: 'AKBP',
    nrp: '76110639',
    jabatan: 'ANALIS KEBIJAKAN MUDA PUSLITBANG POLRI',
    division: 'GASBIN',
    ket: 'IV.B (BIDGASBIN)',
  },
  {
    no: 38,
    name: 'ARIANTO SALKERY, S.H., M.H.',
    rank: 'AKBP',
    nrp: '78041241',
    jabatan: 'ANALIS KEBIJAKAN MUDA BIDGASBIN PUSLITBANG POLRI',
    division: 'GASBIN',
    ket: 'IV.B',
  },
  {
    no: 39,
    name: 'JIMMY PAKPAHAN, S.ST., M.Pd.',
    rank: 'AKBP',
    nrp: '77071375',
    jabatan: 'KASUBBAGUJIMAT BAGLABTEKPOL PUSLITBANG POLRI',
    division: 'TEKPOL',
    ket: 'IV.B DIK',
  },
  {
    no: 40,
    name: 'MARUDUT MANALU, S.H., M.H.',
    rank: 'AKBP',
    nrp: '70070141',
    jabatan: 'PENELITI ILMU KEPOLISIAN MUDA TK I PUSLITBANG POLRI',
    division: 'OPSNAL',
    ket: 'IV.B (BIDGASOPSNAL)',
  },
  {
    no: 41,
    name: 'AHMAD MUNIF, S.H., M.Si.',
    rank: 'PEMBINA TK I',
    nrp: '196912071998031004',
    jabatan: 'KASUBBID BEKUM BIDRIKWASTU PUSLITBANG POLRI',
    division: 'RIKUWASTU',
    ket: 'IV.B',
  },
  {
    no: 42,
    name: 'BUDI TRIYANTO, S.Sos.',
    rank: 'PEMBINA TK I',
    nrp: '197005251996031001',
    jabatan: 'KASUBBIDBINPROF BIDGASBIN PUSLITBANG POLRI',
    division: 'GASBIN',
    ket: 'IV.B',
  },
  {
    no: 43,
    name: 'WILHELMUS SANGA, S.E., M.M.',
    rank: 'PEMBINA',
    nrp: '197805052008121001',
    jabatan: 'KAURKEU PUSLITBANG POLRI',
    division: 'URKEU',
    ket: 'IV.A',
  },
  {
    no: 44,
    name: 'DWI IRAWATI, S.S.',
    rank: 'PEMBINA',
    nrp: '197010021998032002',
    jabatan: 'KAURMIN BIDGASOPSNAL PUSLITBANG POLRI',
    division: 'OPSNAL',
    ket: 'IV.A',
  },
  {
    no: 45,
    name: 'ASEP DARAJAT, S.H., M.H.',
    rank: 'KOMPOL',
    nrp: '77060149',
    jabatan: 'PAUR DOKUMENTASI SUBBAGDOKINFO SETPUSLITBANG POLRI',
    division: 'DOKINFO',
    ket: 'IV.A',
  },
  {
    no: 46,
    name: 'YUDHI RAMAPUTRA, S.E., M.M.',
    rank: 'KOMPOL',
    nrp: '73100155',
    jabatan: 'KASUBBIDFASKON BIDRIKWASTU PUSLITBANG POLRI',
    division: 'RIKUWASTU',
    ket: 'IV.A',
  },

  // Halaman 3 (47 - 71)
  {
    no: 47,
    name: 'NIKEN HERYATI, S.E.',
    rank: 'PEMBINA',
    nrp: '197610092003122001',
    jabatan: 'PAUR RENGAR SUBBAGREN SETPUSLITBANG POLRI',
    division: 'REN',
    ket: 'IV.A',
  },
  {
    no: 48,
    name: 'FEBBRY SUTEDJO, S.Si.',
    rank: 'PEMBINA',
    nrp: '198502082011011002',
    jabatan: 'PAUR SDM SUBBAGSUMDA SETPUSLITBANG POLRI',
    division: 'SUMDA_LOGISTIK',
    ket: 'IV.A',
  },
  {
    no: 49,
    name: 'ENGGAR AGNI WIBOWO, S.Kom., M.H.',
    rank: 'KOMPOL',
    nrp: '82081503',
    jabatan: 'PAUR SUBBID SDM BIDGASBIN PUSLITBANG POLRI',
    division: 'GASBIN',
    ket: 'IV.A',
  },
  {
    no: 50,
    name: 'WELLY APRIANA, S.Kom.',
    rank: 'KOMPOL',
    nrp: '88041120',
    jabatan: 'PAUR INSTANSI SUBBAG KERMA SETPUSLITBANG POLRI',
    division: 'KERMA',
    ket: 'IV.A',
  },
  {
    no: 51,
    name: 'WIBOWO SAPUTRA, S.Pd., S.I.K.',
    rank: 'KOMPOL',
    nrp: '82091339',
    jabatan: 'ANALIS KEBIJAKAN PERTAMA BIDGASBIN PUSLITBANG POLRI',
    division: 'GASBIN',
    ket: 'IV.A',
  },
  {
    no: 52,
    name: 'HELMIADY, S.Si., M.Si.',
    rank: 'KOMPOL',
    nrp: '87051877',
    jabatan: 'PENELITI ILMU KEPOLISIAN MUDA TK III PUSLITBANG POLRI',
    division: 'OPSNAL',
    ket: 'IV.A (BKO)',
  },
  {
    no: 53,
    name: 'HERI SUPRAPTO, S.E., M.A.',
    rank: 'PEMBINA',
    nrp: '197806072008121001',
    jabatan: 'PAUR FUNGSI SUBBAGKERMA SETPUSLITBANG POLRI',
    division: 'KERMA',
    ket: 'IV.A',
  },
  {
    no: 54,
    name: 'FAJAR ISTIONO, S.T.',
    rank: 'PEMBINA',
    nrp: '198109072011011003',
    jabatan: 'KAURMIN BIDGASBIN PUSLITBANG POLRI',
    division: 'GASBIN',
    ket: 'IV.A',
  },
  {
    no: 55,
    name: 'MULYANTO, S.E.',
    rank: 'PENATA TK I',
    nrp: '197211101998031004',
    jabatan: 'PS. KAURMIN BIDRIKWASTU PUSLITBANG POLRI',
    division: 'RIKUWASTU',
    ket: 'III. D',
  },
  {
    no: 56,
    name: 'MINDARTI, S.E.',
    rank: 'PENATA TK I',
    nrp: '198207092008122002',
    jabatan: 'PAUR SUBBAG DOKINFO SETPUSLITBANG POLRI',
    division: 'DOKINFO',
    ket: 'III. D',
  },
  {
    no: 57,
    name: 'DHANNY IRAWAN, S.E.',
    rank: 'PENATA TK I',
    nrp: '198203282009121001',
    jabatan: 'PAMIN SUBBID BINPROF BIDGASBIN PUSLITBANG POLRI',
    division: 'GASBIN',
    ket: 'III. D',
  },
  {
    no: 58,
    name: 'SAEPUDIN ZUHRI, S.A.P',
    rank: 'PENATA TK I',
    nrp: '196911041998031004',
    jabatan: 'PS. PAMIN SUBBAGDOKINFO SET PUSLITBANG',
    division: 'DOKINFO',
    ket: 'III. D',
  },
  {
    no: 59,
    name: 'TRIYANTI, S.E.',
    rank: 'PENATA TK I',
    nrp: '197005202003122003',
    jabatan: 'PAMIN SUBBID GASTIN BIDGASOPSNAL PUSLITBANG POLRI',
    division: 'OPSNAL',
    ket: 'III.D',
  },
  {
    no: 60,
    name: 'YULI PERTIWI, S.E, M.M.',
    rank: 'PENATA TK I',
    nrp: '196907012003122001',
    jabatan: 'P.S. PAUR SUBBIDFASKON BIDRIKWASTU PUSLITBANG POLRI',
    division: 'RIKUWASTU',
    ket: 'III.D',
  },
  {
    no: 61,
    name: 'BUDI PRAYITNO, A. Md., S.M.',
    rank: 'PENATA TK I',
    nrp: '197012261998031001',
    jabatan: 'PAUR SUBBID GASTIN BIDGASOPSNAL PUSLITBANG POLRI',
    division: 'OPSNAL',
    ket: 'III.C',
  },
  {
    no: 62,
    name: 'ANNISAA YUSUF, S.T.K., S.I.K.',
    rank: 'AKP',
    nrp: '92040558',
    jabatan: 'PS. KAURMIN BAGLABTEKPOL PUSLITBANG POLRI',
    division: 'TEKPOL',
    ket: 'III. C',
  },
  {
    no: 63,
    name: 'HANDONO PRIHADI, S.H.',
    rank: 'AKP',
    nrp: '76110077',
    jabatan: 'PS. KATAUD PUSLITBANG POLRI',
    division: 'TAUD',
    ket: 'III. C',
  },
  {
    no: 64,
    name: 'ANINDITYA DICHI SAPTARINI, S.T.',
    rank: 'AKP',
    nrp: '90090317',
    jabatan: 'PS. PAUR SUBBID BEKUM BIDRIKWASTU PUSLITBANG POLRI',
    division: 'RIKUWASTU',
    ket: 'III. C',
  },
  {
    no: 65,
    name: 'GUSTIKA SITANGGANG, S.Si.',
    rank: 'AKP',
    nrp: '93081208',
    jabatan: 'PS. PAUR BINPROF BIDGASBIN PUSLITBANG POLRI',
    division: 'GASBIN',
    ket: 'III.C',
  },
  {
    no: 66,
    name: 'RISTA ERVINA, A.Md. Gz.',
    rank: 'PENATA',
    nrp: '197806182003122004',
    jabatan: 'PS PAURPAL BIDRIKWASTU PUSLITBANG POLRI',
    division: 'RIKUWASTU',
    ket: 'III.C',
  },
  {
    no: 67,
    name: 'BAMBANG ADIWASKITO',
    rank: 'PENATA',
    nrp: '196904171994031003',
    jabatan: 'PAUR TAUD SETPUSLITBANG POLRI',
    division: 'TAUD',
    ket: 'III.C',
  },
  {
    no: 68,
    name: 'AGUS SISWANTO',
    rank: 'PENATA',
    nrp: '197004121994031003',
    jabatan: 'PAMIN URKEU PUSLITBANG POLRI',
    division: 'URKEU',
    ket: 'III.C',
  },
  {
    no: 69,
    name: 'LINDANINGSIH N, S.E.',
    rank: 'PENATA',
    nrp: '197606091999032004',
    jabatan: 'PAMIN SUBBAGREN SETPUSLITBANG POLRI',
    division: 'REN',
    ket: 'III.C',
  },
  {
    no: 70,
    name: 'EMA AMALIA, S.E.',
    rank: 'PENATA',
    nrp: '198409182008122001',
    jabatan: 'PAMIN SUBBAGSUMDA SETPUSLITBANG POLRI',
    division: 'SUMDA_LOGISTIK',
    ket: 'III.C',
  },
  {
    no: 71,
    name: 'PUJI APRILTA SARI, A.Md.',
    rank: 'PENATA',
    nrp: '198204212008122001',
    jabatan: 'PAMIN SUBBIDPAL BIDRIKWASTU PUSLITBANG POLRI',
    division: 'RIKUWASTU',
    ket: 'III.C',
  },

  // Halaman 4 (72 - 91)
  {
    no: 72,
    name: 'RUDY PRIATNA',
    rank: 'PENDA TK I',
    nrp: '196810251990121001',
    jabatan: 'PS PAUR SUBBAGUJISENJATA BAGLABTEKPOL PUSLITBANG POLRI',
    division: 'TEKPOL',
    ket: 'III.B',
  },
  {
    no: 73,
    name: 'KRISTO BAPTISTO SORMIN, S.T.',
    rank: 'IPTU',
    nrp: '95011203',
    jabatan: 'PENELITI ILMU KEPOLISIAN PERTAMA TK. I PUSLITBANG POLRI',
    division: 'TEKPOL',
    ket: 'LAB UJIMAT',
  },
  {
    no: 74,
    name: 'FAJAR AFRIANTO, S.T., M.Si.',
    rank: 'IPTU',
    nrp: '96061315',
    jabatan: 'PENELITI ILMU KEPOLISIAN PERTAMA TK. I PUSLITBANG POLRI',
    division: 'TEKPOL',
    ket: 'LAB TRANSPOR T',
  },
  {
    no: 75,
    name: 'RIZKY DWI PAHLAWAN, S.T.',
    rank: 'IPTU',
    nrp: '96111275',
    jabatan: 'PENELITI ILMU KEPOLISIAN PERTAMA TK. I PUSLITBANG POLRI',
    division: 'TEKPOL',
    ket: 'LAB ELEKTRO',
  },
  {
    no: 76,
    name: 'RIZKI SAPUTRA, S.Stat.',
    rank: 'IPTU',
    nrp: '97010930',
    jabatan: 'PAMIN SUBBIDGASSUS BIDGASOPSNAL PUSLITBANG POLRI',
    division: 'OPSNAL',
    ket: 'III.B',
  },
  {
    no: 77,
    name: 'YULWIDO ADI, S.T., M.Sc.',
    rank: 'IPTU',
    nrp: '97100978',
    jabatan: 'PENELITI ILMU KEPOLISIAN PERTAMA TK. I PUSLITBANG POLRI',
    division: 'TEKPOL',
    ket: 'LAB SENJATA',
  },
  {
    no: 78,
    name: 'VIDO WISNU RAMADHAN, S.T., M.Han.',
    rank: 'IPTU',
    nrp: '96021097',
    jabatan: 'PAMIN SUBBAGUJISARTRANS BAGLABTEKPOL PUSLITBANG POLRI',
    division: 'TEKPOL',
    ket: 'III.B',
  },
  {
    no: 79,
    name: 'KANDAKA WUSKO, S.T.',
    rank: 'IPTU',
    nrp: '97030965',
    jabatan: 'BHAYANGKARA PENYELIA PUSLITBANG POLRI',
    division: 'TEKPOL',
    ket: 'LAB SENJATA (tekpol)',
  },
  {
    no: 80,
    name: 'TEZAR RAKHMAN, S.Tr.K',
    rank: 'IPTU',
    nrp: '99010702',
    jabatan: 'PENELITI ILMU KEPOLISIAN PERTAMA TK II PUSLITBANG POLRI',
    division: 'GASBIN',
    ket: 'III.B GASBIN',
  },
  {
    no: 81,
    name: 'DWIJO SUMARSONO, S.H.',
    rank: 'IPTU',
    nrp: '85080412',
    jabatan: 'PAMIN SUBBAGUJIMAT BAGLABTEKPOL PUSLITBANG POLRI',
    division: 'TEKPOL',
    ket: 'LAB TRANSPORTASI (tekpol)',
  },
  {
    no: 82,
    name: 'SRI SUPARMI',
    rank: 'PENDA TK I',
    nrp: '196910161999032003',
    jabatan: 'PS PAMIN SUBBAGKERMA SET PUSLITBANG POLRI',
    division: 'KERMA',
    ket: 'III.B',
  },
  {
    no: 83,
    name: 'NUR TEGUH MULYAWAN, S.E.',
    rank: 'PENDA TK I',
    nrp: '198008092002121006',
    jabatan: 'PAMIN VERIF URKEU PUSLITBANG POLRI',
    division: 'URKEU',
    ket: 'III.B',
  },
  {
    no: 84,
    name: 'BAHRINEL SIREGAR',
    rank: 'PENDA TK I',
    nrp: '198111062003121004',
    jabatan: 'PAMIN DATA URKEU PUSLITBANG POLRI',
    division: 'URKEU',
    ket: 'III.B',
  },
  {
    no: 85,
    name: 'DWI INDRYULI, A.Md.',
    rank: 'PENDA TK I',
    nrp: '197907152006042003',
    jabatan: 'BANUM TAUD SETPUSLITBANG POLRI',
    division: 'TAUD',
    ket: 'III.B',
  },
  {
    no: 86,
    name: 'ALFIAN SETYO NUGROHO, S.T.',
    rank: 'IPTU',
    nrp: '99111038',
    jabatan: 'PENELITI ILMU KEPOLISIAN PERTAMA TK.II PUSLITBANG POLRI',
    division: 'RIKUWASTU',
    ket: 'III.A (BIDRIKWASTU)',
  },
  {
    no: 87,
    name: 'RACHMAT TAUFIK HIDAYATULLOH',
    rank: 'IPDA',
    nrp: '86040033',
    jabatan: 'PS PAMIN SUBBID SDM BIDGASBIN PUSLITBANG POLRI',
    division: 'GASBIN',
    ket: 'III.A',
  },
  {
    no: 88,
    name: 'DESSY ARIYANI',
    rank: 'PENDA',
    nrp: '197810042006042004',
    jabatan: 'PAMIN SUBBIDBEKUM BIDRIKWASTU PUSLITBANG POLRI',
    division: 'RIKUWASTU',
    ket: 'III.A',
  },
  {
    no: 89,
    name: "SITI MUSRIFATUN NI'MAH",
    rank: 'PENDA',
    nrp: '198209232003122002',
    jabatan: 'BANUM URKEU SETPUSLITBANG POLRI',
    division: 'URKEU',
    ket: 'III.A',
  },
  {
    no: 90,
    name: 'DWI NATALIA ANGGRAINI, S.K.M.',
    rank: 'PENDA',
    nrp: '198007042006042023',
    jabatan: 'BANUM TAUD SETPUSLITBANG POLRI',
    division: 'TAUD',
    ket: 'III.A',
  },
  {
    no: 91,
    name: 'NURHASANAH',
    rank: 'PENDA',
    nrp: '197312122007012004',
    jabatan: 'BANUM SUBBAGKERMA SET PUSLITBANG POLRI',
    division: 'KERMA',
    ket: 'III.A',
  },

  // Halaman 5 (92 - 115)
  {
    no: 92,
    name: 'NUR ALIH, S.E.',
    rank: 'PENDA',
    nrp: '197407052008101001',
    jabatan: 'BANUM SUBBAGSUMDA SETPUSLITBANG POLRI',
    division: 'SUMDA_LOGISTIK',
    ket: 'III.A',
  },
  {
    no: 93,
    name: 'TOTO MARTONO, S.IP.',
    rank: 'PENDA',
    nrp: '197903272008011001',
    jabatan: 'BANUM SUBBAGSUMDA SETPUSLITBANG POLRI',
    division: 'SUMDA_LOGISTIK',
    ket: 'III.A',
  },
  {
    no: 94,
    name: 'WIDY HARI WIBOWO',
    rank: 'PENDA',
    nrp: '198602092008121001',
    jabatan: 'BANUM URKEU PUSLITBANG POLRI',
    division: 'URKEU',
    ket: 'III.A',
  },
  {
    no: 95,
    name: 'FIRMAN MAULIDI',
    rank: 'PENDA',
    nrp: '198102012009101001',
    jabatan: 'BANUM TAUD SET PUSLITBANG POLRI',
    division: 'TAUD',
    ket: 'III.A',
  },
  {
    no: 96,
    name: 'NURKHOLIK',
    rank: 'PENDA',
    nrp: '198210262009101001',
    jabatan: 'BANUM TAUD SETPUSLITBANG POLRI',
    division: 'TAUD',
    ket: 'III.A',
  },
  {
    no: 97,
    name: 'SUTAN ANDREAS PARLINDUNGAN, S.T.',
    rank: 'IPDA',
    nrp: '97120984',
    jabatan: 'PAMIN SUBBAGUJI SENJATA BAGLABTEKPOL PUSLITBANG POLRI',
    division: 'TEKPOL',
    ket: 'III.A',
  },
  {
    no: 98,
    name: 'MARADON',
    rank: 'IPDA',
    nrp: '87080791',
    jabatan: 'PAMA BIDGASOPSNAL PUSLITBANG POLRI',
    division: 'OPSNAL',
    ket: 'III.A',
  },
  {
    no: 99,
    name: 'DEWI HANDANI, S.H., M.M.',
    rank: 'IPDA',
    nrp: '89100534',
    jabatan: 'BHAYANGKARA PENYELIA SUBBAGDOKINFO PUSLITBANG POLRI',
    division: 'DOKINFO',
    ket: 'III.A',
  },
  {
    no: 100,
    name: 'AJENG HANANINGRUM, S.Stat.',
    rank: 'IPDA',
    nrp: '98100882',
    jabatan: 'PAMA BIDGASOPSNAL PUSLITBANG POLRI',
    division: 'OPSNAL',
    ket: 'III.A',
  },
  {
    no: 101,
    name: 'HARDIANSYAH, S.H., M.H.',
    rank: 'IPDA',
    nrp: '89100255',
    jabatan: 'PS. PAMIN SUBBIDFASKON BIDRIKWASTU PUSLITBANG POLRI',
    division: 'RIKUWASTU',
    ket: 'III.A',
  },
  {
    no: 102,
    name: 'I WAYAN BHARATA RISABHA, S.Kom.',
    rank: 'AIPDA',
    nrp: '86110023',
    jabatan: 'BAMIN SUBBAGSUMDA SETPUSLITBANG POLRI',
    division: 'SUMDA_LOGISTIK',
    ket: 'II.E',
  },
  {
    no: 103,
    name: 'MUHAMMAD AGUNG SITORUS, S.H.',
    rank: 'BRIPKA',
    nrp: '89120490',
    jabatan: 'BAMIN TAUD SETPUSLITBANG POLRI',
    division: 'TAUD',
    ket: 'II.D',
  },
  {
    no: 104,
    name: 'DARMONO',
    rank: 'PENGATUR TK I',
    nrp: '198504062003121002',
    jabatan: 'BANUM BAGLABTEKPOL PUSLITBANG POLRI',
    division: 'TEKPOL',
    ket: 'II.D',
  },
  {
    no: 105,
    name: 'LILISETIYOWATI',
    rank: 'PENGATUR TK I',
    nrp: '197808252002122004',
    jabatan: 'BANUM TAUD SETPUSLITBANG POLRI',
    division: 'TAUD',
    ket: 'II.D',
  },
  {
    no: 106,
    name: 'MOHAMAD DARYADI',
    rank: 'PENGATUR TK I',
    nrp: '197605042003121005',
    jabatan: 'BANUM TAUD SETPUSLITBANG POLRI',
    division: 'TAUD',
    ket: 'II.D',
  },
  {
    no: 107,
    name: 'SUBUH PRIYANTO, A. Md. Ak.',
    rank: 'PENGATUR TK I',
    nrp: '197904032005011009',
    jabatan: 'BANUM TAUD SETPUSLITBANG POLRI',
    division: 'TAUD',
    ket: 'II.D',
  },
  {
    no: 108,
    name: 'SYAFRIANA FRANSISKA, S.A.P.',
    rank: 'BRIGPOL',
    nrp: '95090051',
    jabatan: 'BAMIN SUBBAGDOKINFO SETPUSLITBANG POLRI',
    division: 'DOKINFO',
    ket: 'II.C',
  },
  {
    no: 109,
    name: 'RIFKA SONIA SETYOWATI, S.M.',
    rank: 'BRIGPOL',
    nrp: '96020191',
    jabatan: 'BAMIN SUBBAGSUMDA SETPUSLITBANG POLRI',
    division: 'SUMDA_LOGISTIK',
    ket: 'II.C',
  },
  {
    no: 110,
    name: 'JUNIVINDA ZOGARA',
    rank: 'BRIGPOL',
    nrp: '97060151',
    jabatan: 'BAMIN BIDRIKWASTU PUSLITBANG POLRI',
    division: 'RIKUWASTU',
    ket: 'II.C',
  },
  {
    no: 111,
    name: 'SENJA PUTRI AYU',
    rank: 'BRIGPOL',
    nrp: '94020299',
    jabatan: 'BANUM BIDGASOPSNAL PUSLITBANG POLRI',
    division: 'OPSNAL',
    ket: 'II.C',
  },
  {
    no: 112,
    name: 'ORI VA MALQUNA, S.ST.',
    rank: 'BRIPTU',
    nrp: '95111152',
    jabatan: 'BAMIN TAUD SETPUSLITBANG POLRI',
    division: 'TAUD',
    ket: 'II.B (BKO)',
  },
  {
    no: 113,
    name: 'LEONARDO SITORUS PANE, S.T.',
    rank: 'BRIPTU',
    nrp: '96081324',
    jabatan: 'BAMIN LAB SENJATA BAGLABTEKPOL PUSLITBANG POLRI',
    division: 'TEKPOL',
    ket: 'LAB SENJATA',
  },
  {
    no: 114,
    name: 'ROBI WARDIANSYAH, S.Psi.',
    rank: 'BRIPTU',
    nrp: '00060188',
    jabatan: 'BAMIN BIDGASBIN PUSLITBANG POLRI',
    division: 'GASBIN',
    ket: 'II.B',
  },
  {
    no: 115,
    name: 'DEDEN WAHYUDIN, S.M.',
    rank: 'BRIPTU',
    nrp: '97120855',
    jabatan: 'BAMIN TAUD SETPUSLITBANG POLRI',
    division: 'TAUD',
    ket: 'II.B (BKO)',
  },

  // Halaman 6 (116 - 129)
  {
    no: 116,
    name: 'MELLINIA FITRIKA IRJAYANTI, S.S.',
    rank: 'BRIPTU',
    nrp: '00010015',
    jabatan: 'BAMIN BIDGASBIN PUSLITBANG POLRI',
    division: 'GASBIN',
    ket: 'II.B',
  },
  {
    no: 117,
    name: 'BEBA TIASITA RESTU INTAN',
    rank: 'BRIPTU',
    nrp: '98080788',
    jabatan: 'BAMIN SUBBAGKERMA SETPUSLITBANG POLRI',
    division: 'KERMA',
    ket: 'II.B',
  },
  {
    no: 118,
    name: 'IKHWAN ABDILLAH MAKHFUD, S.H.',
    rank: 'BRIPTU',
    nrp: '98091508',
    jabatan: 'BAMIN BIDGASOPSNAL PUSLITBANG POLRI',
    division: 'OPSNAL',
    ket: 'II.B',
  },
  {
    no: 119,
    name: 'HANDRIAN WIBIANIKA, S.Pd.',
    rank: 'BRIPTU',
    nrp: '99080539',
    jabatan: 'BAMIN BAGLABTEKPOL PUSLITBANG POLRI',
    division: 'TEKPOL',
    ket: 'LAB ALMATSUS',
  },
  {
    no: 120,
    name: 'DIDAN RAMADAN',
    rank: 'BRIPTU',
    nrp: '99120561',
    jabatan: 'BAMIN BAGLABTEKPOL PUSLITBANG POLRI',
    division: 'TEKPOL',
    ket: 'LAB SENJATA',
  },
  {
    no: 121,
    name: 'HAFEZ AL GHANY',
    rank: 'BRIPTU',
    nrp: '99040698',
    jabatan: 'BAMIN SUBBAGREN SETPUSLITBANG POLRI',
    division: 'REN',
    ket: 'II.B',
  },
  {
    no: 122,
    name: 'ANDIKA BAHARI SURACHMAN',
    rank: 'BRIPTU',
    nrp: '99050621',
    jabatan: 'BHAYANGKARA PELAKSANA PEMULA SUBBAGDOKINFO PUSLITBANG POLRI',
    division: 'DOKINFO',
    ket: 'II.B',
  },
  {
    no: 123,
    name: 'RICO YALDI',
    rank: 'BRIPTU',
    nrp: '99120352',
    jabatan: 'BAMIN TAUD SETPUSLITBANG POLRI',
    division: 'TAUD',
    ket: 'II.B',
  },
  {
    no: 124,
    name: 'AHMAD SAEFUDIN, S.H.',
    rank: 'BRIPTU',
    nrp: '00030380',
    jabatan: 'BAMIN LAB TRANSPORTASI BAGLABTEKPOL PUSLITBANG POLRI',
    division: 'TEKPOL',
    ket: 'II.B',
  },
  {
    no: 125,
    name: 'NOOR KEMAL RACHMANTO, S.F.',
    rank: 'BRIPTU',
    nrp: '01010132',
    jabatan: 'BANUM LAB ELEKTRO BAGLABTEKPOL PUSLITBANG POLRI',
    division: 'TEKPOL',
    ket: 'II.B',
  },
  {
    no: 126,
    name: 'MUHAMMAD AFWI ASSHOBRI HARAHAP',
    rank: 'BRIPDA',
    nrp: '03090477',
    jabatan: 'BAMIN SUBBAGREN SETPUSLITBANG POLRI',
    division: 'REN',
    ket: 'II.A',
  },
  {
    no: 127,
    name: 'FATHUR RAHMAN GHANI',
    rank: 'BRIPDA',
    nrp: '04050200',
    jabatan: 'BAMIN SUBBAGDOKINFO SETPUSLITBANG POLRI',
    division: 'DOKINFO',
    ket: 'II.A',
  },
  {
    no: 128,
    name: 'DEDI HIDAYAT',
    rank: 'PENGDA',
    nrp: '196905132014121001',
    jabatan: 'BANUM TAUD SETPUSLITBANG POLRI',
    division: 'TAUD',
    ket: 'II.A',
  },
  {
    no: 129,
    name: 'JUITA SAHARA',
    rank: 'PPPK',
    nrp: '197901182025212003',
    jabatan: 'PPPK TAUD SETPUSLITBANG POLRI',
    division: 'TAUD',
    ket: 'V',
  },
];

